### ISSUE TITLE
No damage to bad roles.

### ISSUE THREAD

**Issue by dok441** [TTT-2/ttt2-role_pri#1]
I don't noticed that if I shoot the traitor, I've dealt 30 damage to his death, in the logs there and he is healthy as an ox.

**Comment by TimGoll** [comment]
You do not deal any damage to the traitor since shooting him kills you instantly

**Comment by dok441** [comment]
In the role of 30 written as a detective and then death...

**Comment by lebroomer** [comment]
@TimGoll you should set Primary.Damage to zero

**Comment by TimGoll** [comment]
But you said traitor. And yes, you deal 30 damage to detevtives

**Comment by dok441** [comment]
shooting other evil roles kills the priest while still damaging them like detectives

**Comment by TimGoll** [comment]
Ahh, this is an error in the description, my bad. I'll edit it
