### ISSUE TITLE
The weapon is good, but not round 2

### ISSUE THREAD

**Issue by dok441** [TTT-2/ttt2-role_pri#2]
A person can have Saint deagle in the next round.

**Comment by TimGoll** [comment]
I have a suspicion. I will look into it

**Comment by TimGoll** [comment]
I added a workaround for this until we fix this in TTT2. Please test.

**Comment by dok441** [comment]
Still not fixed, if go in observers and back, then weapons will emerge in a new round with the other role.

**Comment by TimGoll** [comment]
Hm, It wasn't happening for me anymore. I'll test it in the following days
