### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by dok441** [TTT-2/ttt2-role_pri#5]
Local file is overriding addon's file! lua/includes/modules/hook.lua (Srlion's Hook Library)
[ERROR] addons/ttt2-role_pri-master/lua/autorun/sh_priest_handler.lua:347: attempt to call method 'SteamID64' (a nil value)
  1. IsBrother - addons/ttt2-role_pri-master/lua/autorun/sh_priest_handler.lua:347
   2. v - addons/ttt2-role_pri-master/lua/autorun/client/cl_priest_targetid.lua:15
    3. Run - lua/includes/modules/hook.lua:84
     4. Call - gamemodes/terrortown/gamemode/client/cl_targetid.lua:286
      5. unknown - gamemodes/terrortown/gamemode/client/cl_hud_manager.lua:118

**Comment by TimGoll** [comment]
This problem seems to be caused by "srlion's hook library"
Either way, if SteamID 64 is not defined, there's likely another error in your game.

**Comment by dok441** [comment]
At that time, it was just her.

**Comment by TimGoll** [comment]
Her?

**Comment by Satton2** [comment]
@TimGoll 
In our language, word «error» (ошибка) has a feminine gender. Because of that and the fact that dok441 uses some machine translation, he wrote «her».

He probably wanted to say: «At the time, there was only it (this error).»

**Comment by TimGoll** [comment]
Ah thanks! 
I can look into this tomorrow and I can maybe add a safety check here. But this error is strange and shouldn't happen
In the future it would really help me of you'd describe the situation to reproduce the bug

**Comment by TimGoll** [comment]
I attempted to fix this isse, could you please test? Thanks!
