### ISSUE TITLE
targetID problems with tData = nil

### ISSUE THREAD

**Issue by dok441** [TTT-2/ttt2-role_pri#6]
[ERROR] addons/ttt2-role_pri-master/lua/autorun/client/cl_priest_targetid.lua:8: attempt to call method 'GetEntity' (a nil value)
  1. v - addons/ttt2-role_pri-master/lua/autorun/client/cl_priest_targetid.lua:8
   2. Run - lua/includes/modules/hook.lua:84
    3. Call - gamemodes/terrortown/gamemode/client/cl_targetid.lua:302
     4. unknown - gamemodes/terrortown/gamemode/client/cl_hud_manager.lua:118

**Comment by TimGoll** [comment]
I can't reproduce this. It does not happen for me. Please reopen once you know the source of the problem.

**Comment by TimGoll** [comment]
Okay, so we investigated this a bit further. The only scenario where this error could happen is if an addon sets `tData` to `nil` or overwrites it in the `TTTRenderEntityInfo` hook. I don't know which addon does this, but it seems like it happens to you. Maybe you could check which addon uses this hook.

**Comment by TimGoll** [comment]
Could you update us with some additional information? I'm still not able to reproduce this

**Comment by dok441** [comment]
The problem is no longer there.
