### ISSUE TITLE
A missed translation

### ISSUE THREAD

**Issue by dok441** [TTT-2/ttt2-role_pri#8]
Please add to the translation file, the name of the weapon and in the table the designation of who is in the brotherhood as indicated in the screenshot.
![таб](https://user-images.githubusercontent.com/7480655/80127236-b7026000-859c-11ea-8327-6a2ed0ed520b.png)

**Comment by dok441** [comment]
When will you finish it?!

**Comment by TimGoll** [comment]
once I have time to do so^^

**Comment by TimGoll** [comment]
well, I'm working on it right now!
