### ISSUE TITLE
Immortality

### ISSUE THREAD

**Issue by dok441** [TTT-2/ttt2-role_pri#9]
As you can see in the screenshot, I am dead, I see my body and my killer, but I can speak in the table I am alive. This is due to this role.
![эм](https://user-images.githubusercontent.com/7480655/80134929-2762ae80-85a8-11ea-9686-21d25f7a130c.png)

**Comment by TimGoll** [comment]
Hmm, this role does not change anything about the voice chat

**Comment by dok441** [comment]
I say that I am alive when I die with this role and can talk to living people.

**Comment by TimGoll** [comment]
Also please add more information:
I need at least the TTT2 version and the priest version

**Comment by TimGoll** [comment]
I can test it, but this role does change nothing about the death... seems strange. Also no one else has this problem

**Comment by dok441** [comment]
The latest version of both the priest and the mode version. All changes that are currently made in the mode and in the role.

**Comment by TimGoll** [comment]
latest on steam or on github? was it always broken? or recently?

**Comment by dok441** [comment]
Find errors
[ERROR] addons/ttt2-role_pri-master/lua/autorun/sh_priest_handler.lua:351: bad argument #1 to 'pairs' (table expected, got nil)
  1. pairs - [C]:-1
   2. GetBrotherhood - addons/ttt2-role_pri-master/lua/autorun/sh_priest_handler.lua:351
    3. RemoveFromBrotherhood - addons/ttt2-role_pri-master/lua/autorun/sh_priest_handler.lua:229
     4. BrotherDies - addons/ttt2-role_pri-master/lua/autorun/sh_priest_handler.lua:205
      5. fn - addons/ttt2-role_pri-master/lua/autorun/sh_priest_handler.lua:294
       6. unknown - addons/ulib/lua/ulib/shared/hook.lua:109
        7. OFireBullets - [C]:-1
         8. FireBullets - addons/leyhitreg/lua/autorun/server/sv_leyhitreg.lua:245
          9. ShootBullet - gamemodes/terrortown/entities/weapons/weapon_tttbase.lua:398
           10. unknown - gamemodes/terrortown/entities/weapons/weapon_tttbase.lua:299

**Comment by dok441** [comment]
I use the github version

**Comment by TimGoll** [comment]
I think I have fixed this. I haven't tested it though. Please test and reopen if it still exists
